apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.10.1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "5050"
        envFrom:
        - configMapRef:
            name: cloud-config
